/* Blind-Test Player — Mondial · TikTok · Hits EN · IA marocain */
window.TRACKS = [
  {
    id: 1,
    titre: 'Dai Dai',
    artiste: 'Shakira & Burna Boy',
    categorie: 'MONDIAL_2026',
    trend: 'Hymne officiel FIFA · viral Reels',
    reelOuIa: 'réel',
    mp3: 'audio/01-dai-dai.mp3',
    indice: 'Coupe du Monde 2026',
  },
  {
    id: 2,
    titre: 'Lighter',
    artiste: 'Jelly Roll & Carín León',
    categorie: 'MONDIAL_2026',
    trend: 'Album officiel FIFA 2026',
    reelOuIa: 'réel',
    mp3: 'audio/02-lighter.mp3',
    indice: 'Country × Mexique',
  },
  {
    id: 3,
    titre: 'How You Like Me Now?',
    artiste: 'The Heavy',
    categorie: 'TENDANCE_INTL',
    trend: 'Highlights sport · Reels foot',
    reelOuIa: 'réel',
    mp3: 'audio/03-how-you-like-me-now.mp3',
    indice: 'Rock indie',
  },
  {
    id: 4,
    titre: 'Dumbo',
    artiste: 'Travis Scott',
    categorie: 'TIKTOK_IG',
    trend: 'JackBoys 2 · trend TikTok juillet 2026',
    reelOuIa: 'réel',
    mp3: 'audio/04-travis-dumbo.mp3',
    indice: 'Trap · edit TikTok',
  },
  {
    id: 5,
    titre: 'FE!N',
    artiste: 'Travis Scott feat. Playboi Carti',
    categorie: 'TIKTOK_IG',
    trend: 'Son ultra-connu sur TikTok/Reels',
    reelOuIa: 'réel',
    mp3: 'audio/05-travis-fein.mp3',
    indice: 'UTOPÍA · millions de edits',
  },
  {
    id: 6,
    titre: 'Do Your Dance',
    artiste: 'RIIZE',
    categorie: 'TIKTOK_IG',
    trend: '100M+ vues TikTok · dance challenge',
    reelOuIa: 'réel',
    mp3: 'audio/06-riize-do-your-dance.mp3',
    indice: 'K-pop · choré Insta',
  },
  {
    id: 7,
    titre: 'Gut Genug',
    artiste: 'Blumengarten & Kitschkrieg',
    categorie: 'TIKTOK_IG',
    trend: 'Mème viral TikTok/IG',
    reelOuIa: 'réel',
    mp3: 'audio/07-gut-genug.mp3',
    indice: 'Son mème · edits Reels',
  },
  {
    id: 8,
    titre: 'Morocco World Cup 2026',
    artiste: 'Michi feat. Nora Fatehi & Achraf Hakimi',
    categorie: 'MONDIAL_2026',
    trend: 'Hymne supporters Maroc',
    reelOuIa: 'réel',
    mp3: 'audio/08-morocco-wc2026.mp3',
    indice: 'Foot',
  },
  {
    id: 9,
    titre: 'Espresso',
    artiste: 'Sabrina Carpenter',
    categorie: 'HITS_EN',
    trend: 'Hit mondial · partout sur TikTok',
    reelOuIa: 'réel',
    mp3: 'audio/09-espresso.mp3',
    indice: 'Pop anglaise · 2024-25',
  },
  {
    id: 10,
    titre: 'Blinding Lights',
    artiste: 'The Weeknd',
    categorie: 'HITS_EN',
    trend: 'Ultra-connu · Reels · jeux vidéo',
    reelOuIa: 'réel',
    mp3: 'audio/10-blinding-lights.mp3',
    indice: 'Synth-pop 80s',
  },
  {
    id: 11,
    titre: 'Flowers',
    artiste: 'Miley Cyrus',
    categorie: 'HITS_EN',
    trend: 'Grammy · viral TikTok dance',
    reelOuIa: 'réel',
    mp3: 'audio/11-flowers.mp3',
    indice: 'Pop · self-love anthem',
  },
  {
    id: 12,
    titre: 'Chaâbi AI Cover',
    artiste: 'Généré IA (style MA)',
    categorie: 'IA_MAROC',
    trend: 'Vague covers chaâbi IA sur TikTok Maroc',
    reelOuIa: 'ia',
    mp3: 'audio/12-chaabi-ai-maroc.mp3',
    indice: 'Voix trop lisse ? · bendir',
  },
  {
    id: 13,
    titre: 'نايضة يا لالة',
    artiste: 'Suno AI · chaâbi marocain',
    categorie: 'IA_MAROC',
    trend: 'Chaâbi 100% généré · Darija · Suno',
    reelOuIa: 'ia',
    mp3: 'audio/13-suno-chaabi-maroc.mp3',
    indice: 'Bendir · fête · IA',
  },
  {
    id: 14,
    titre: 'Raï AI Cover',
    artiste: 'Généré IA (style MA)',
    categorie: 'IA_MAROC',
    trend: 'Reprises raï/chaâbi IA · TikTok MA',
    reelOuIa: 'ia',
    mp3: 'audio/14-rai-ai-maroc.mp3',
    indice: 'Artefacts · mélodie « trop parfaite »',
  },
];

window.CAT_LABELS = {
  MONDIAL_2026: { label: 'Mondial 2026', color: '#46D6A8' },
  TENDANCE_INTL: { label: 'Tendance intl', color: '#43C6FF' },
  TIKTOK_IG: { label: 'TikTok / Insta', color: '#FF7A4D' },
  HITS_EN: { label: 'Hits anglais', color: '#FFC93C' },
  IA_MAROC: { label: 'IA marocain', color: '#B69CFF' },
};
